apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bib-wildcard
  namespace: bib-prod
spec:
  secretName: bib-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.bib.internal"
    - bib.internal
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
