apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: bib-strict-mtls
  namespace: bib-prod
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: bib-strict-mtls
  namespace: bib-staging
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: bib-strict-mtls
  namespace: bib-dev
spec:
  mtls:
    mode: STRICT
